### ISSUE TITLE
Do you have any plans to make actual release?

### ISSUE THREAD

**Issue by kloczek** [NVIDIA/eglexternalplatform#2]
It would be good to mark current code base as release :)

**Comment by mvicomoya** [comment]
Huh, yes. Creating corresponding tags now...

**Comment by mvicomoya** [comment]
Both [1.0](https://github.com/NVIDIA/eglexternalplatform/releases/tag/1.0) and [1.1](https://github.com/NVIDIA/eglexternalplatform/releases/tag/1.1) tags have been created.

**Comment by kloczek** [comment]
Thank you :)
